eureka:
  client:
    serviceUrl:
       defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  application:
     name: peav-apigateway

server:
  port: 8080
zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Access-Control-Expose-Headers, Access-Control-Allow-Methods
  ignore-security-headers: true
  routes:
    kie:
      path: /kie/**
      serviceId: PEAV-KIE-SERVER
        
